<script>
    require([
        'jquery',
        'slick'
    ], function ($) {

      $(document).ready(function () {
        $(".after-nav-slider").slick({
            dots: false,
            arrows: false,
            infinite: true,
            speed: 300,
            centerMode: true,
            cssEase: 'linear',
            centerPadding: '0px',
            slidesToShow: 3,
            responsive: [
              {
                breakpoint: 960,
                settings: {
                  arrows: false,
                  centerMode: true,
                  slidesToShow: 2
                }
              },
              {
                breakpoint: 600,
                settings: {
                  arrows: false,
                  centerMode: true,
                  slidesToShow: 1,
                  autoplay:true,
                  autoplaySpeed:2000
                }
              }
            ]
        });
      });


      $('button.action.tocart').on('click', function(){
        $('[data-block="minicart"]').one('contentUpdated', function ()  {
            $('[data-block="minicart"]').find('[data-role="dropdownDialog"]').dropdownDialog("open");
            setTimeout(function(){
              $('[data-block="minicart"]').find('[data-role="dropdownDialog"]').dropdownDialog("close");
            },4000);
        });
      });



      $(window).scroll(function () {
          if( $(window).scrollTop() > $('.top-container').offset().top && !($('.top-container').hasClass('sticky'))){
          $('.top-container').addClass('sticky');
          } else if ($(window).scrollTop() == 0){
          $('.top-container').removeClass('sticky');
          }
      });

    });
</script>
