<?php
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $storeManager = $objectManager->get('Magento\Store\Model\StoreManagerInterface');
    $store = $storeManager->getStore();
    $mediaUrl = $store->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
?>

<div class="blocks">
  <div id="three-blocks" class="carousel owl-carousel">
    <div class="item">
      <img src="<?php echo $mediaUrl ;?>/wysiwyg/strawberry.png" alt="strawberry"/>
    </div>
    <div class="item">
      <img src="<?php echo $mediaUrl ;?>/wysiwyg/almonds.png" alt="strawberry"/>
    </div>
    <div class="item">
      <img src="<?php echo $mediaUrl ;?>/wysiwyg/oil.png" alt="oil" />
    </div>
  </div>
</div>
<script>
    require([
        'jquery',
        'owlcarouselslider'
        ], function (jQuery) {
        jQuery("#three-blocks").owlCarousel({
            autoPlay: 3000,
            margin:10,
            navigation : false,
            pagination : false,
						responsive:{
			        0:{
			            items:1,
			            nav:false
			        },
			        767:{
			            items:1,
			            nav:false
			        },
			        768:{
			            items:3,
			            nav:false,
			            loop:false
			        }
				    }
        });
    });
</script>
