<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 *
 * @var $block \Magento\Customer\Block\Account\Forgotpassword
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Account\Forgotpassword $block */
?>
<?php $sitekey = $this->helper('WTW\Seller\Helper\Sitekey'); ?>
<form class="form password forget"
      action="<?= $block->escapeUrl($block->getUrl('*/*/forgotpasswordpost')) ?>"
      method="post"
      id="form-validate"
      data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>">
        <div class="field note"><?= $block->escapeHtml(__('Please enter your email address below to receive a password reset link.')) ?></div>
        <div class="field email required">
            <div class="control">
                <input type="email" name="email" alt="email" placeholder="<?= $block->escapeHtml(__('Email')) ?>" id="email_address" class="input-text" value="<?= $block->escapeHtmlAttr($block->getEmailValue()) ?>" data-mage-init='{"mage/trim-input":{}}' data-validate="{required:true, 'validate-email':true}">
            </div>
        </div>
        <?= $block->getChildHtml('form_additional_info') ?>
        <div class="field form-group required">
            <div class="g-recaptcha required" id="recaptcha" data-sitekey="<?php echo $sitekey->getCaptchaSitekey() ?>" data-size="invisible">
            </div>
            <div style="display:none" id="captcha-error-msg">
                  <span><?php echo __('Please Validate Re-captcha') ?></span>
             </div>
        </div>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action submit primary"><span><?= $block->escapeHtml(__('Reset My Password')) ?></span></button>
        </div>
        <div class="secondary">
            <a class="action back" href="<?= $block->escapeUrl($block->getLoginUrl()) ?>"><span><?= $block->escapeHtml(__('Go back')) ?></span></a>
        </div>
    </div>
</form>
<script src="https://www.google.com/recaptcha/api.js" type="text/javascript" xml="space"></script>
