<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var $block Magento\Bundle\Block\Catalog\Product\View\Type\Bundle */ ?>
<?php
$product = $block->getProduct();
$helper = $this->helper('Magento\Catalog\Helper\Output');
$stripSelection = $product->getConfigureMode() ? true : false;
$options = $block->decorateArray($block->getOptions($stripSelection));
?>
<div class="create-own">
<div class="create-own-top">
    <?php if ($product->isSaleable()):?>
        <?php if (count($options)): ?>
    <script type="text/x-magento-init">
        {
            "#product_addtocart_form": {
                "priceBundle": {
                    "optionConfig": <?= /* @escapeNotVerified */ $block->getJsonConfig() ?>,
                    "controlContainer": ".field.option"
                }
            }
        }
    </script>

    <legend id="customizeTitle" class="legend title">
                <span><?= /* @escapeNotVerified */ __('Customize %1', $helper->productAttribute($product, $product->getName(), 'name')) ?></span>
            </legend><br />
    <?= $block->getChildHtml('product_info_bundle_options_top') ?>
</div>
    <div class="selected-items-m">
        <div class="selected-items">Select Below Items </div>
        <div id="selected-items-count"></div>
    </div>
</div>
        <div id="super-product-bundle" class="fieldset fieldset-bundle-options" data-mage-init='{"mage/tabs": {"openedState": "active", "animate": {"duration": 100}, "active": 0, "disabledState": "disabled"}}'>

            <?php foreach ($options as $option): ?>
                <?php if (!$option->getSelections()): ?>
                    <?php continue; ?>
                <?php endif; ?>
                <?= $block->getOptionHtml($option) ?>
            <?php endforeach; ?>
        </div>
    <?php else: ?>
        <p class="empty"><?= /* @escapeNotVerified */ __('No options of this product are available.') ?></p>
    <?php endif; ?>
<?php endif;?>
