<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\CatalogWidget\Block\Product\ProductsList $block */
$fbpixHelper = false;
try{
    $fbpixHelper = $this->helper(\SixtySeven\Ajaxcart\Helper\Fbpixel::class);
} catch(\Exception $e){
    $fbpixHelper = false;
}
?>
<?php if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())): ?>
<?php

    $_mmProductHelper = $this->helper('WTW\Marketplace\Helper\ProductVendor');
    $storeUrlHelper = $this->helper('WTW\CatalogWidgetFix\Helper\StoreUrl');
    $type = 'widget-product-grid';

    $mode = 'grid';

    $image = 'new_products_content_widget_grid';
    $items = $block->getProductCollection()->getItems();
    $sectionImage = $block->getData('section_image');
    $sectionUrl = $block->getData('section_url');
    $showWishlist = true;
    $showCompare = true;
    $showCart = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::DEFAULT_VIEW;
    $description = false;
?>
    <div class="block widget block-products-list <?= /* @noEscape */ $mode ?>">
        <?php if ($block->getTitle()): ?>
        <div class="block-title">
            <strong><?= $block->escapeHtml(__($block->getTitle())) ?></strong>
        </div>
        <?php endif ?>
        <div class="block-content">
            <?= /* @noEscape */ '<!-- ' . $image . '-->' ?>
            <div class="products-<?= /* @noEscape */ $mode ?> <?= /* @noEscape */ $mode ?>">
             <ol class="product-items <?= /* @noEscape */ $type ?>">
                    <?php $iterator = 1; ?>
                    <?php if(!empty($sectionImage)): ?>
                        <li class="pro-shop-all">
                          <img class="lazyload" data-src="<?= $storeUrlHelper->getMediaUrl($sectionImage); ?>">
                          <?php if(!empty($sectionUrl)): ?>
                            <a class="button shop-all-btn" href="<?= $storeUrlHelper->getUrlByPath($sectionUrl); ?>">
                              <?= __('Shop all') ?>
                            </a>
                          <?php endif; ?>
                        </li>
                    <?php endif; ?>
                    <?php foreach ($items as $_item): ?>
                        <?php $hasOption = $_item->getTypeInstance()->hasOptions($_item); ?>
                        <?php if ($iterator++ != 1): ?></li><?php endif ?>
                        <li class="item product product-item">
                        <div class="product-item-info">
                           <?php
 if($_item->getShowOrganicLabel()=='1'){ ?>
<span class="organic-badge">
  <img src="<?= /* @escapeNotVerified */ $block->getViewFileUrl('images/all-organic.png') ?>"
       alt="<?= /* @escapeNotVerified */ __('All Organic') ?>">
</span>
<?php } ?>
                            <a href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>" class="product-item-photo">
                                <?= $block->getImage($_item, $image)->toHtml() ?>
                            </a>
                            <div class="product details product-item-details">
                                <strong class="product-item-name">
                                    <a title="<?= $block->escapeHtml($_item->getName()) ?>"
                                       href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"
                                       class="product-item-link">
                                        <?= $block->escapeHtml($_item->getName()) ?>
                                    </a>
                                </strong>
                                <?php //$vendor = $_mmProductHelper->getSellerInfoByProductId($_item->getId());
                                    //if($vendor):
                                ?>
                                    <p><?php /*echo __('By <a href="%2">%1</a>', $vendor->getShopName(), $_mmProductHelper->getCategoryUrlById($vendor->getCategoryId()))*/ ?></p>
                                <?php //endif; ?>

                                <?php if ($templateType): ?>
                                    <?= $block->getReviewsSummaryHtml($_item, $templateType) ?>
                                <?php endif; ?>

                                <?php if ($showWishlist || $showCompare || $showCart): ?>
                                    <div class="product-item-actions">
                                        <?php if ($showCart): ?>
                                          <?= $block->getProductDetailsHtml($_item) ?>
                                          <div class="atc-price-combined">
                                            <div class="price-section-wrapper">
                                              <?php
                                              echo $block->getProductPriceHtml($_item, $type);
                                              ?>
                                            </div>
                                            <div class="atc-div" data-bind="scope: 'qtysection'">
                                              <div class="actions-primary">
                                                    <?php if($fbpixHelper): ?>
                                                        <span data-fbpixel='<?= json_encode($fbpixHelper->getProductData($_item, $block)); ?>' style="display: none;"></span>
                                                    <?php endif; ?>
                                                  <?php if ($_item->isSaleable()): ?>
                                                    <?php
                                                              $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                                              $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
                                                          ?>
                                                      <?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
                                                          <button style="display: none;" data-bind="visible: true" data-post='<?= /* @noEscape */ $postData ?>' class="action tocart primary" type="button"
                                                                      title="<?= $block->escapeHtml(__('Add')) ?>"
                                                                      class="action tocart primary" data-typeid="<?= $_item->getTypeId() ?>">
                                                                  <span><?= /* @escapeNotVerified */ $block->escapeHtml(__('Add')) ?></span>
                                                              </button>
                                                      <?php else: ?>
                                                          <div class="atc-div-inner">

                                                            <?php if(!$hasOption): ?>    
                                                              <!-- ko if: getItemInfoById(<?= $_item->getId() ?>)!='' -->
                                                              <div class="control qty" style="display: none;" data-bind="visible: true">
                                                                  <button type="button"   id="<?= /* @escapeNotVerified */ $_item->getId() ?>-dec"  class="decreaseQty" data-post='<?= /* @noEscape */ $postData ?>'>-</button>
                                                                  <input id="cart-<?= /* @escapeNotVerified */ $_item->getId() ?>-qty"
                                                                     name="cart[<?= /* @escapeNotVerified */ $_item->getId() ?>][qty]"
                                                                     data-cart-item-id="<?= /* @escapeNotVerified */ $_item->getSku() ?>"
                                                                     data-bind="value: getItemInfoById(<?= $_item->getId() ?>)"
                                                                     type="number"
                                                                     size="4"
                                                                     title="<?= $block->escapeHtml(__('Qty')) ?>"
                                                                     class="input-text qty"
                                                                     data-validate="{required:true,'validate-greater-than-zero':true}"
                                                                     data-role="cart-item-qty" readonly/>
                                                                  <button type="button"  id="<?= /* @escapeNotVerified */ $_item->getId() ?>-upt" class="increaseQty" data-post='<?= /* @noEscape */ $postData ?>'>+</button>

                                                               </div>
                                                              <!-- /ko -->
                                                            <?php endif; ?>  

                                                            <?php if(!$hasOption): ?> 
                                                              <!-- ko if: qtysection().isEmpty || getItemInfoById(<?= $_item->getId() ?>)=='' -->
                                                              <button style="display: none;" data-bind="visible: true" data-post='<?= /* @noEscape */ $postData ?>' class="action tocart primary" type="button"
                                                                      title="<?= $block->escapeHtml(__('Add')) ?>"
                                                                      class="action tocart primary">
                                                                  <span><?= /* @escapeNotVerified */ $block->escapeHtml(__('Add')) ?></span>
                                                              </button>
                                                              <!-- /ko -->
                                                            <?php else: ?>
                                                                <button style="display: none;" data-bind="visible: true" data-post='<?= /* @noEscape */ $postData ?>' class="action tocart primary" type="button" data-typeid="<?= $_item->getTypeId() ?>"
                                                                        title="<?= $block->escapeHtml(__('Add')) ?>"
                                                                        class="action tocart primary">
                                                                    <span><?= /* @escapeNotVerified */ $block->escapeHtml(__('Add')) ?></span>
                                                                </button>
                                                            <?php endif; ?>  

                                                          </div>
                                                      <?php endif; ?>
                                                  <?php else: ?>
                                                      <?php if ($_item->getIsSalable()): ?>
                                                          <div class="stock available"><span><?= $block->escapeHtml(__('In stock')) ?></span></div>
                                                      <?php else: ?>
                                                          <div class="stock unavailable"><span><?= $block->escapeHtml(__('Out of stock')) ?></span></div>
                                                      <?php endif; ?>
                                                  <?php endif; ?>
                                              </div>
                                            </div>

         

                                          </div>
                                          
                                          <div class="atc-incart-div atc-div" data-bind="scope: 'qtysection'">
                                            <!-- ko if: getItemInfoById(<?= $_item->getId() ?>)!='' -->
                                            <div class="control qty" style="display: none;" data-bind="visible: true" >
                                                <div class="add-text-BG" id="cart_qty_txt-<?= /* @escapeNotVerified */ $_item->getId() ?>"><span data-bind="text: getItemInfoById(<?= $_item->getId() ?>)+ ' in basket'"></span></div>
                                            </div>
                                            <!-- /ko -->
                                          </div>
                                          <div class="product-del-info">Delivering in <span class="load-delivery-info-span"><span class="load-delivery-info">Brighton &amp; nearby</span></span> only.</div>

                                        <?php if($_item->getChangeCustomTextColor()=='1'): ?>
                                          <div class="product-del-info highlight-text" style="color:#ff0057; display:block">
                                            <?php echo $_item->getData('custom_text_in_listing'); ?>
                                          </div>
                                        <?php else : ?>
                                          <div class="product-del-info" style="display:block">
                                            <?php echo $_item->getData('custom_text_in_listing'); ?>
                                          </div>
                                        <?php endif; ?>
                                        
                                        <?php endif; ?>
                                        <?php if ($showWishlist || $showCompare): ?>
                                            <div class="actions-secondary" data-role="add-to-links">
                                                <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist): ?>
                                                    <a href="#"
                                                       data-post='<?= /* @noEscape */ $block->getAddToWishlistParams($_item) ?>' class="action towishlist" data-action="add-to-wishlist" title="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>">
                                                        <span><?= $block->escapeHtml(__('Add to Wish List')) ?></span>
                                                    </a>
                                                <?php endif; ?>
                                                <?php if ($block->getAddToCompareUrl() && $showCompare): ?>
                                                    <?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');?>
                                                    <a href="#" class="action tocompare" data-post='<?= /* @noEscape */ $compareHelper->getPostDataParams($_item) ?>' title="<?= $block->escapeHtmlAttr(__('Add to Compare')) ?>">
                                                        <span><?= $block->escapeHtml(__('Add to Compare')) ?></span>
                                                    </a>
                                                <?php endif; ?>
                                            </div>
                                        <?php endif; ?>
                                    </div>
                                <?php endif; ?>
                            </div>
                        </div>
                        <?= ($iterator == count($items)+1) ? '</li>' : '' ?>
                    <?php endforeach ?>
                </ol>
            </div>
            <?= $block->getPagerHtml() ?>
        </div>
    </div>
    <script type="text/x-magento-init">
        {
            "*": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "qtysection": {
                            "component": "SixtySeven_Ajaxcart/js/qtysection"
                        }
                    }
                }
            }
        }
    </script>
<?php endif;?>
