<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>

<?php

$_productCollection = $block->getLoadedProductCollection();
$cartHelper = $this->helper('Magento\Checkout\Helper\Cart');
$_helper = $this->helper('Magento\Catalog\Helper\Output');
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?= /* @escapeNotVerified */ __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
    <?= $block->getToolbarHtml() ?>
    <?= $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $imageDisplayArea = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $imageDisplayArea = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <?= $block->getToolbarHtml() ?>
    <div class="products wrapper <?= /* @escapeNotVerified */ $viewMode ?> products-<?= /* @escapeNotVerified */ $viewMode ?>">
        <ol class="products list items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product): ?>


            <li class="item product product-item">
                <div class="product-item-info" data-container="product-<?= /* @escapeNotVerified */ $viewMode ?>">


                    <?php
                    $productImage = $block->getImage($_product, $imageDisplayArea);
                    if ($pos != null) {
                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;"';
                    }
                    ?>
                    <?php // Product Image ?>
                    <a href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                        <?= $productImage->toHtml() ?>
                    </a>
                    <div class="product details product-item-details">
                        <?php
                            $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                        ?>
                        <strong class="product name product-item-name">
                            <a class="product-item-link"
                               href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>">
                                <?= /* @escapeNotVerified */ $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                            </a>
                        </strong>
                        <?= $block->getReviewsSummaryHtml($_product, $templateType) ?>
                        <?= $block->getProductDetailsHtml($_product) ?>

                        <div class="atc-div" data-bind="scope: 'qtysection'">
                        <div class="product actions product-item-actions"<?= strpos($pos, $viewMode . '-actions') ? $position : '' ?>>
                              <div class="actions-primary"<?= strpos($pos, $viewMode . '-primary') ? $position : '' ?>>
                                  <?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?>

                            <?php if ($_product->isSaleable()): ?>
                                <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                <?php if($_product->getBoxType()) { ?>
                                     <form class="cateprod" data-role="tocart-form" data-product-sku="<?= $block->escapeHtml($_product->getSku()) ?>" action="<?= $cartHelper->getAddUrl($_product); ?>" method="post">
                                         <input type="hidden" name="product" value="<?= $block->escapeHtmlAttr($postParams['data']['product']) ?>" />

                                         <input type="hidden" name="<?= /* @noEscape */ Action::PARAM_NAME_URL_ENCODED ?>" value="<?= /* @noEscape */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>" />
                                                                    <?= $block->getBlockHtml('formkey') ?>



                                        <!-- ko if: getItemInfoById(<?= $_product->getId() ?>)!='' -->

                                         <div class="control qty" style="display: none;" data-bind="visible: true">
                                        <button type="button"   id="<?= /* @escapeNotVerified */ $_product->getId() ?>-dec"  class="decreaseQty">-</button>
                                       <input id="cart-<?= /* @escapeNotVerified */ $_product->getId() ?>-qty"
                                           name="cart[<?= /* @escapeNotVerified */ $_product->getId() ?>][qty]"
                                           data-cart-item-id="<?= /* @escapeNotVerified */ $_product->getSku() ?>"
                                           data-bind="value: getItemInfoById(<?= $_product->getId() ?>)"
                                           type="number"
                                           size="4"
                                           title="<?= $block->escapeHtml(__('Qty')) ?>"
                                           class="input-text qty"
                                           data-validate="{required:true,'validate-greater-than-zero':true}"
                                           data-role="cart-item-qty" readonly/>
                                           <button type="button"  id="<?= /* @escapeNotVerified */ $_product->getId() ?>-upt" class="increaseQty">+</button>


                                         <div class="add-text-BG" id="cart_qty_txt-<?= /* @escapeNotVerified */ $_product->getId() ?>"><span data-bind="text: getItemInfoById(<?= $_product->getId() ?>)+ ' in basket'"></span></div>
                                         </div>

                                            <!-- /ko -->





                                        <!-- ko if: qtysection().isEmpty || typeof qtysection().itemsinfo=='undefined' || typeof qtysection().itemsinfo[<?= $_product->getId() ?>]=='undefined' -->
                                        <button style="display: none;" data-bind="visible: true" type="submit"
                                                title="<?= $block->escapeHtml(__('Add')) ?>"
                                                class="action tocart primary">
                                            <span><?= /* @escapeNotVerified */ __('Add') ?></span>
                                        </button>

                                        <!-- /ko -->





                                     </form>
                                <?php } else {?>

                                <form class="cateprod" data-role="tocart-form" data-product-sku="<?= $block->escapeHtml($_product->getSku()) ?>" action="<?= /* @NoEscape */ $postParams['action'] ?>" method="post">

                                    <input type="hidden" name="product" value="<?= /* @escapeNotVerified */ $postParams['data']['product'] ?>">
                                    <input type="hidden" name="<?= /* @escapeNotVerified */ Action::PARAM_NAME_URL_ENCODED ?>" value="<?= /* @escapeNotVerified */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                    <?= $block->getBlockHtml('formkey') ?>

                                        <!-- ko if: getItemInfoById(<?= $_product->getId() ?>)!='' -->
                                        <div class="control qty" style="display: none;" data-bind="visible: true">

                                        <button type="button"   id="<?= /* @escapeNotVerified */ $_product->getId() ?>-dec"  class="decreaseQty">-</button>
                                       <input id="cart-<?= /* @escapeNotVerified */ $_product->getId() ?>-qty"
                                           name="cart[<?= /* @escapeNotVerified */ $_product->getId() ?>][qty]"
                                           data-cart-item-id="<?= /* @escapeNotVerified */ $_product->getSku() ?>"
                                           data-bind="value: getItemInfoById(<?= $_product->getId() ?>)"
                                           type="number"
                                           size="4"
                                           title="<?= $block->escapeHtml(__('Qty')) ?>"
                                           class="input-text qty"
                                           data-validate="{required:true,'validate-greater-than-zero':true}"
                                           data-role="cart-item-qty" readonly/>
                                           <button type="button"  id="<?= /* @escapeNotVerified */ $_product->getId() ?>-upt" class="increaseQty">+</button>

                                            </div>

                                         <div class="add-text-BG" id="cart_qty_txt-<?= /* @escapeNotVerified */ $_product->getId() ?>"><span data-bind="text: getItemInfoById(<?= $_product->getId() ?>)+ ' in basket'"></span></div>
                                            <!-- /ko -->





                                        <!-- ko if: qtysection().isEmpty || getItemInfoById(<?= $_product->getId() ?>)=='' -->
                                        <button style="display: none;" data-bind="visible: true" type="submit"
                                                title="<?= $block->escapeHtml(__('Add to basket')) ?>"
                                                class="action tocart primary">
                                            <span><?= /* @escapeNotVerified */ __('Add to basket') ?></span>
                                        </button>
                                        <!-- /ko -->




                                </form>

                                <?php } ?>

                            <?php else: ?>
                                <?php if ($_product->isAvailable()): ?>
                                    <div class="stock available"><span><?= /* @escapeNotVerified */ __('In stock') ?></span></div>
                                <?php else: ?>
                                    <div class="stock unavailable"><span><?= /* @escapeNotVerified */ __('Out of stock') ?></span>
                                    </div>
                                <?php endif; ?>
                            <?php endif; ?>
                            </div>
                        </div>
                        </div>
                        <div class="intro-label">
                            <?php $introLabel = $_product->getIntroLabel();
                                if($introLabel):
                            ?>
                                <small><?php echo $introLabel; ?></small>
                            <?php endif; ?>
                        </div>
                    </div>
                    <div data-role="add-to-wishlist-links" class="actions-secondary">
                        <?php
                        $wishlistIcon = $block->getChildBlock('addtoaction.wishlist');
                        //var_dump(get_class_methods($wishlistIcon)); die;
                        if($wishlistIcon):
                            echo $wishlistIcon->setProduct($_product)->toHtml() ;
                        endif;
                        ?>
                    </div>
                </div>
            </li>
            <?php endforeach; ?>
        </ol>
    </div>
    <?= $block->getToolbarHtml() ?>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {
                    "product_sku": "<?= /* @NoEscape */ $_product->getSku() ?>"
                }
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "qtysection": {
                        "component": "SixtySeven_Ajaxcart/js/qtysection"
                    }
                }
            }
        }
    }
</script>

<script type="text/x-magento-init">
    {
        "[data-role=tocart-form], .cateprod": {
            "catalogAddToCart": {}
        }
    }
</script>
