<a href="<?= $block->getUrl('customer/account',['_secure'=>true]) ?>" class="quick-menu about-dd"
          tabindex="0"
          data-toggle="dropdown"
          data-mage-init='{"dropdown":{"activeClass": "_active"}}' data-bind="scope: 'customer'">
    	<!-- ko if: customer().firstname  -->
    	<i style="display: none;" data-bind="visible: true" class="icon black-user-icon-online"></i>
		<!-- /ko -->
		<!-- ko ifnot: customer().firstname  -->
		<i class="icon black-user-icon"></i>
		<span>Sign In</span>	
		<!-- /ko -->
</a>
<ul data-target="dropdown" class="account link wrapper field-tooltip-content"  data-bind="scope: 'customer'">
	<li>
	  <!-- ko if: customer().firstname  -->
	  <a href="<?php echo $this->getUrl('customer/account/'); ?>"><?php echo __('My Account') ?></a>
	  <!-- /ko -->
	  <!-- ko ifnot: customer().firstname  -->
	  <a style="display: none;" data-bind="visible: true" href="<?php echo $this->getUrl('customer/account/create'); ?>"><?php echo __('Create an Account') ?></a>
	  <!-- /ko -->
	</li>
	<li style="display: none;" data-bind="visible: true">
	  <!-- ko if: customer().firstname  -->
	  <a style="display: none;" data-bind="visible: true" href="<?php echo $this->getUrl('customer/account/logout'); ?>"><?php echo __('Sign Out') ?></a>
	  <!-- /ko -->
	  <!-- ko ifnot: customer().firstname  -->
	  <a style="display: none;" data-bind="visible: true" href="<?php echo $this->getUrl('customer/account/login'); ?>"><?php echo __('Sign In') ?></a>
	  <!-- /ko -->
	</li>
</ul>
<script type="text/x-magento-init">
{
  "*": {
      "Magento_Ui/js/core/app": {
          "components": {
              "customer": {
                  "component": "Magento_Customer/js/view/customer"
              }
          }
      }
  }
}
</script>