<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
$fbpixHelper = false;
try{
    $fbpixHelper = $this->helper(\SixtySeven\Ajaxcart\Helper\Fbpixel::class);
} catch(\Exception $e){
    $fbpixHelper = false;
}
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_specialSection = $this->helper('WTW\Asoshornav\Helper\SpecialSection');
$count = $_productCollection->count();
$_specialSectionVal = '';
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?= /* @escapeNotVerified */ __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
    <?= $block->getToolbarHtml() ?>
    <?= $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $image = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
        $_specialSectionVal = $_specialSection->getSpecialConfigValue();
    } else {
        $viewMode = 'list';
        $image = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
<div class="top-pagination"><?= $block->getToolbarHtml() ?></div>
    <div class="products wrapper <?= /* @escapeNotVerified */ $viewMode ?> products-<?= /* @escapeNotVerified */ $viewMode ?>">
        <?php $iterator = 1; ?>
        <ol class="products list items product-items test 121">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product): ?>
                <?php $hasOption = $_product->getTypeInstance()->hasOptions($_product); ?>
                <?= /* @escapeNotVerified */ ($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>

                <div class="product-item-info" data-container="product-grid">

                    <?php
 if($_product->getShowOrganicLabel()=='1'){ ?>
<span class="organic-badge">
  <img src="<?= /* @escapeNotVerified */ $block->getViewFileUrl('images/all-organic.png') ?>"
       alt="<?= /* @escapeNotVerified */ __('All Organic') ?>">
</span>
<?php } ?>
                    <?php
                    $productImage = $block->getImage($_product, $image);
                    if ($pos != null) {
                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;"';
                    }
                    ?>
                    <?php // Product Image ?>
                    <a href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                        <?= $productImage->toHtml() ?>
                    </a>
                    <div class="product details product-item-details">
                        <?php
                            $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                        ?>
                        <strong class="product name product-item-name">
                            <a class="product-item-link"
                               href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>">
                                <?= /* @escapeNotVerified */ $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                            </a>
                        </strong>
                        <span>
                        <?php
                            $stockLevel = (int)$_product->getStockLevel();
                            if($stockLevel && $stockLevel>0 && $stockLevel<=10){
                                echo __('Less than <strong>%1</strong> left in stock', $stockLevel);
                            }
                        ?>
                        </span>
                        <?php //$block->getReviewsSummaryHtml($_product, $templateType) ?>

                        <?= $block->getProductDetailsHtml($_product) ?>

                        <div class="product-item-inner">
                            <div class="product actions product-item-actions"<?= strpos($pos, $viewMode . '-actions') ? $position : '' ?>>
                                <div class="atc-price-combined">
                                    <div class="price-section-wrapper"><?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?></div>
                                    <div class="atc-div" data-bind="scope: 'qtysection'">

                                        <div class="actions-primary"<?= strpos($pos, $viewMode . '-primary') ? $position : '' ?>>
                                            <?php if ($_product->isSaleable()): ?>
                                                <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                                <form data-role="tocart-form" data-product-sku="<?=  /* @NoEscape */ $_product->getSku() ?>" action="<?= /* @NoEscape */ $postParams['action'] ?>" method="post">

                                                    <?php if($fbpixHelper): ?>
                                                        <span data-fbpixel='<?= json_encode($fbpixHelper->getProductData($_product, $block)); ?>' style="display: none;"></span>
                                                    <?php endif; ?>

                                                    <input type="hidden" name="product" value="<?= /* @escapeNotVerified */ $postParams['data']['product'] ?>">
                                                    <input type="hidden" name="<?= /* @escapeNotVerified */ Action::PARAM_NAME_URL_ENCODED ?>" value="<?= /* @escapeNotVerified */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                                    <?= $block->getBlockHtml('formkey') ?>

                                                <?php if(!$hasOption): ?>
                                                    <!-- ko if: getItemInfoById(<?= $_product->getId() ?>)!='' -->
                                                    <div class="control qty" style="display: none;" data-bind="visible: true">
                                                        <button type="button"   id="<?= /* @escapeNotVerified */ $_product->getId() ?>-dec"  class="decreaseQty">-</button>
                                                        <input id="cart-<?= /* @escapeNotVerified */ $_product->getId() ?>-qty"
                                                           name="cart[<?= /* @escapeNotVerified */ $_product->getId() ?>][qty]"
                                                           data-cart-item-id="<?= /* @escapeNotVerified */ $_product->getSku() ?>"
                                                           data-bind="value: getItemInfoById(<?= $_product->getId() ?>)"
                                                           type="number"
                                                           size="4"
                                                           title="<?= $block->escapeHtml(__('Qty')) ?>"
                                                           class="input-text qty"
                                                           data-validate="{required:true,'validate-greater-than-zero':true}"
                                                           data-role="cart-item-qty" readonly/>
                                                        <button type="button"  id="<?= /* @escapeNotVerified */ $_product->getId() ?>-upt" class="increaseQty">+</button>
                                                     </div>
                                                    <!-- /ko -->
                                                <?php endif; ?>

                                                <?php if(!$hasOption): ?>
                                                    <!-- ko if: qtysection().isEmpty || getItemInfoById(<?= $_product->getId() ?>)=='' -->
                                                    <button style="display: none;" data-bind="visible: true" type="submit"
                                                            title="<?= $block->escapeHtml(__('Add')) ?>"
                                                            class="action tocart primary">
                                                        <span><?= /* @escapeNotVerified */ __('Add') ?></span>
                                                    </button>
                                                    <!-- /ko -->
                                                <?php else: ?>
                                                    <button style="display: none;" data-bind="visible: true" type="submit" data-typeid="<?= $_product->getTypeId() ?>"
                                                            title="<?= $block->escapeHtml(__('Add')) ?>"
                                                            class="action tocart primary">
                                                        <span><?= /* @escapeNotVerified */ __('Add') ?></span>
                                                    </button>
                                                <?php endif; ?>

                                                </form>
                                            <?php else: ?>
                                                <?php if ($_product->isAvailable()): ?>
                                                    <div class="stock available"><span><?= /* @escapeNotVerified */ __('In stock') ?></span></div>
                                                <?php else: ?>
                                                    <div class="stock unavailable"><span><?= /* @escapeNotVerified */ __('Out of stock') ?></span></div>
                                                <?php endif; ?>
                                            <?php endif; ?>
                                        </div>
                                    </div>
                                </div>

                                <div class="atc-incart-div atc-div" data-bind="scope: 'qtysection'">
                                    <!-- ko if: getItemInfoById(<?= $_product->getId() ?>)!='' -->
                                    <div class="control qty" style="display: none;" data-bind="visible: true" >
                                        <div class="add-text-BG" id="cart_qty_txt-<?= /* @escapeNotVerified */ $_product->getId() ?>">
                                            <span data-bind="text: getItemInfoById(<?= $_product->getId() ?>)+ ' in basket'"></span>
                                        </div>
                                    </div>
                                    <!-- /ko -->
                                </div>
                                <!-- <div class="product-del-info">Delivering in <span class="load-delivery-info-span"><span class="load-delivery-info">Brighton &amp; nearby</span></span> only.</div> -->

                                <?php if($_product->getChangeCustomTextColor()=='1'): ?>
                                  <div class="product-del-info highlight-text" style="color:#ff0057; display:block">
                                    <?php echo $_product->getData('custom_text_in_listing'); ?>
                                  </div>
                                <?php else : ?>
                                  <div class="product-del-info" style="display:block">
                                    <?php echo $_product->getData('custom_text_in_listing'); ?>
                                  </div>
                                <?php endif; ?>



                                <div data-role="add-to-links" class="actions-secondary"<?= strpos($pos, $viewMode . '-secondary') ? $position : '' ?>>
                                    <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                                        <?= $addToBlock->setProduct($_product)->getChildHtml() ?>
                                    <?php endif; ?>
                                </div>
                            </div>
                            <?php if ($showDescription):?>
                                <div class="product description product-item-description">
                                    <?= /* @escapeNotVerified */ $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                    <a href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>" title="<?= /* @escapeNotVerified */ $_productNameStripped ?>"
                                       class="action more"><?= /* @escapeNotVerified */ __('Learn More') ?></a>
                                </div>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
                <?= ($iterator == count($_productCollection)+1) ? '</li>' : '' ?>

                <?php
                $hasSpecial = (!empty($_specialSectionVal) && (($count<9 && $count==$iterator-1) || $iterator==10))? true: false;
                if($hasSpecial==true): ?>
                    <?= /* @escapeNotVerified */ ($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>

                    <div class="product-item-info">
                        <?= $_specialSectionVal ?>
                    </div>

                    <?= ($iterator == count($_productCollection)+1) ? '</li>' : '' ?>
                <?php endif; ?>

            <?php endforeach; ?>
        </ol>
    </div>
    <?= $block->getToolbarHtml() ?>

    <script type="text/x-magento-init">
        {
            "*": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "qtysection": {
                            "component": "SixtySeven_Ajaxcart/js/qtysection"
                        }
                    }
                }
            }
        }
    </script>

    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {
                    "product_sku": "<?= /* @NoEscape */ $_product->getSku() ?>"
                }
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>

<script type="text/javascript">
    require(['jquery'], function($){
        $(window).on('load', function() {
            setTimeout(function(){
                $(".swatch-attribute-options").prop("selectedIndex", 1).change();
            }, 4000);
        });

        $(document).on("contentUpdated", function(){
            setTimeout(function(){ 
                $(".swatch-attribute-options").prop("selectedIndex", 1).change();
            }, 3000);
        });
    });
</script>
